#! /bin/sh

if tty=$(tty 2> /dev/null); then
	pgrep -t "${tty#/dev/}" -x sxhkd > /dev/null || sxhkd &
else
	pgrep -x sxhkd > /dev/null || sxhkd &
fi

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#00BCD4"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox:*:Picture-in-Picture sticky=on state=floating
bspc rule -a Thunderbird desktop=^8
bspc rule -a *:*:alsamixer sticky=on state=floating
bspc rule -a ipydropdown sticky=on state=floating hidden=on
bspc rule -a Zathura state=tiled

# Desktop
xrb -load ~/.Xresources
~/.config/polybar/nord/launch.sh
nitrogen --restore &

# Autostarts
pgrep picom > /dev/null || picom -b &
pgrep thunderbird > /dev/null || thunderbird &
pgrep pcloud > /dev/null || pcloud &
pgrep ipystart > /dev/null || termite --class ipydropdown -e 'ipystart -i' &

